<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Privacy Policy | BFI Education Services</title>
    <link rel="icon" type="image/png" sizes="32x32" href="/img/bfi.webp">
    <link rel="icon" type="image/png" sizes="16x16" href="/img/bfi.webp">
    <link rel="apple-touch-icon" href="/img/bfi.webp">
    <link rel="shortcut icon" href="/img/bfi.webp">
    <meta name="description" content="Privacy Policy for BFI Education Services (BFI SIS). Learn how we collect, use, and protect your personal data.">

    @vite(['resources/css/app.css'])
    
</head>
<body class="bg-gray-50 text-gray-900 antialiased font-sans">

    <div class="min-h-screen py-12 px-4 sm:px-6 lg:px-8">
        <article class="max-w-4xl mx-auto bg-white shadow-sm rounded-lg overflow-hidden p-8 sm:p-12">
            
            {{-- Header --}}
            <header class="mb-10 border-b pb-6">
                <h1 class="text-3xl sm:text-4xl font-extrabold text-gray-900 tracking-tight mb-2">
                    Privacy Policy
                </h1>
                <p class="text-sm text-gray-500 italic">
                    Last updated: August 30, 2023
                </p>
            </header>

            {{-- Body Content --}}
            <div class="space-y-6 text-gray-700 leading-relaxed">
                <p>
                    This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </p>

                <p>
                    We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                </p>

                {{-- Interpretation --}}
                <section>
                    <h2 class="text-2xl font-bold text-gray-800 mt-8 mb-4">Interpretation and Definitions</h2>
                    
                    <h3 class="text-xl font-semibold text-gray-800 mt-4 mb-2">Interpretation</h3>
                    <p>
                        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.
                    </p>

                    <h3 class="text-xl font-semibold text-gray-800 mt-6 mb-2">Definitions</h3>
                    <p class="mb-4">For the purposes of this Privacy Policy:</p>
                    
                    <ul class="list-disc pl-6 space-y-3">
                        <li><strong>Account:</strong> A unique account created for You to access our Service or parts of our Service.</li>
                        <li><strong>Affiliate:</strong> An entity that controls, is controlled by, or is under common control with a party.</li>
                        <li><strong>Application:</strong> Refers to BFI SIS, the software program provided by the Company.</li>
                        <li><strong>Company:</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to BFI Education Services, No.235, Shu Khinn Thar Myo Pat Rd, Township.</li>
                        <li><strong>Country:</strong> Refers to Myanmar (Burma).</li>
                        <li><strong>Device:</strong> Any device that can access the Service such as a computer, a cellphone, or a digital tablet.</li>
                        <li><strong>Personal Data:</strong> Any information that relates to an identified or identifiable individual.</li>
                        <li><strong>Service:</strong> Refers to the Application.</li>
                        <li><strong>Service Provider:</strong> Any natural or legal person who processes the data on behalf of the Company.</li>
                        <li><strong>Usage Data:</strong> Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                        <li><strong>You:</strong> The individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                    </ul>
                </section>

                {{-- Data Collection --}}
                <section>
                    <h2 class="text-2xl font-bold text-gray-800 mt-8 mb-4">Collecting and Using Your Personal Data</h2>
                    
                    <h3 class="text-xl font-semibold text-gray-800 mt-4 mb-2">Types of Data Collected</h3>
                    
                    <h4 class="font-bold text-gray-800 mt-2">Personal Data</h4>
                    <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                    <ul class="list-disc pl-6 mt-2">
                        <li>Usage Data</li>
                    </ul>

                    <h4 class="font-bold text-gray-800 mt-4">Usage Data</h4>
                    <p class="mt-2">Usage Data is collected automatically when using the Service.</p>
                    
                    <h4 class="font-bold text-gray-800 mt-4">Information Collected while Using the Application</h4>
                    <p>While using Our Application, We may collect, with Your prior permission:</p>
                    <ul class="list-disc pl-6 mt-2">
                        <li>Information regarding your location</li>
                    </ul>
                </section>

                {{-- Contact Section --}}
                <section class="bg-blue-50 p-6 rounded-lg mt-8">
                    <h2 class="text-2xl font-bold text-blue-900 mb-4">Contact Us</h2>
                    <p class="text-blue-800">If you have any questions about this Privacy Policy, You can contact us:</p>
                    <ul class="list-disc pl-6 mt-2 text-blue-800">
                        <li>
                            By visiting this page on our website: 
                            <a href="https://www.bfi.edu.mm/community/contact_us" class="underline hover:text-blue-600 transition duration-150 ease-in-out">
                                https://www.bfi.edu.mm/community/contact_us
                            </a>
                        </li>
                    </ul>
                </section>

            </div>
        </article>
    </div>
</body>
</html>